from typing import Optional, Any, Dict
import logging


class StandardLogger:
    """
        Standard Logger to handle application logging using logging module.
        @param name: Optional[str] - Name of the logger, default is the class name
        @param dir: Optional[str] - Directory to save log files, default is 'None' (no file logging)
    """
    def __init__(self, name: Optional[str] = None, dir: Optional[str] = None) -> None: ...
    def console_handler(self) -> None: ...
    def file_handler(self) -> None: ...
    def info(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...

class StructLogger:
    """
        Logger wrapper for structlog (JSON structured logging).
    """
    def __init__(self, name: Optional[str] = None, dir: Optional[str] = None) -> None: ...
    def console_handler(self) -> None: ...
    def file_handler(self) -> None: ...
    def info(self, message: str, **kwargs: Any) -> None: ...
    def debug(self, message: str, **kwargs: Any) -> None: ...
    def warn(self, message: str, **kwargs: Any) -> None: ...
    def error(self, message: str, **kwargs: Any) -> None: ...
    def critical(self, message: str, **kwargs: Any) -> None: ...

class SeriLogger:
    """
        Logger wrapper for serilog-python.
    """
    def __init__(self, name: Optional[str] = None, dir: Optional[str] = None) -> None: ...
    def console_handler(self) -> None: ...
    def file_handler(self) -> None: ...
    def info(self, message: str, **kwargs: Any) -> None: ...
    def debug(self, message: str, **kwargs: Any) -> None: ...
    def warn(self, message: str, **kwargs: Any) -> None: ...
    def error(self, message: str, **kwargs: Any) -> None: ...
    def critical(self, message: str, **kwargs: Any) -> None: ...
