class Logger:
    def __init__(self, name: str, dir: str) -> None: ...
    def console_handler(self) -> None: ...
    def file_handler(self) -> None: ...
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...
    def critical(self, msg: str) -> None: ...